---
- name: yum | install yum-utils package
  yum:
    name: yum-utils
    state: present

- name: yum_repo | add docker repository
  shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: yum | install docker packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: services | start and enable service docker on boot
  systemd:
    name: docker
    state: started
    enabled: yes

- name: install | download docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  when: install_docker_compose == true
