---
- name: yum | install yum-utils package
  yum:
    name: yum-utils
    state: present

- name: yum_repo | add docker repository
  yum_repository:
    name: Docker CE Stable - x86_64
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: yum | install docker packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: services | start and enable service docker on boot
  systemd:
    name: docker
    state: started
    enabled: yes
